version: "3"

services:
  mc:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      VERSION: "1.16.5"
      MEMORY: "6G"
      ONLINE_MODE: "false" # Para permitir cuentas no premium
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      - ./minecraft-data:/data # Volumen para persistencia de datos
